class Cfg:
    CAMERA_ID = 0
    FLIP_H = True

    FRAME_WIDTH = 960
    FRAME_HEIGHT = 540
    CAMERA_FPS = 24

    SMOOTH_ALPHA = 0.18
    VEL_BOOST_THRESHOLD = 80
    VEL_BOOST_ALPHA = 0.45

    DEAD_ZONE = 8

    CLICK_THRESH = 30
    PINCH_RELEASE = 52

    DRAG_HOLD_FRAMES = 16
    CLICK_COOLDOWN = 0.30
    PAUSE_COOLDOWN = 1.20

    PALM_OPEN_FINGERS = 4

    SAFE_TOP_BAR = 90
    ENABLE_CLICK_ACTIONS = True